language: java
jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Vk2LQJbCIQDNKDl06pER5dWYi8kfUE+gmPI9x+9bCMxTABcquZ+F0h2+doa9jOu6lQY8pW9yhE+SV0cYoYctOuUYYbXKoZMbIcz76o6IQ0yMB6uUxbw+HS99qqkeE2LCXn4si6876VaWjBvdCC4rSIlOCHXnaYAsMr766fW+dR0="

addons:
  coverity_scan:
    project:
      name: "konradrenner/jxattr"
      description: "java library for accessing extended file attributes (comments, tags, etc), defined by the freedesktop project"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command: mvn  clean install -DskipTests=true -B -V
    branch_pattern: master
