language: java
jdk:
  - oraclejdk8
  
script: mvn -f jxattr/pom.xml test
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "mvXinQDh34UcJnfd/v2CMVco3C/d4Ki7/lR2zgff3NfpHlrKjZL1NanT/RzqmBlnnGH319dfSXNfAWRIcBhC2Zmar/MDk0OxhhlC7lBtskGR2T7pfTD20HsVJlk4p2VU5x399LOObxUCPA1WvmUoXeaIYCnIB3PGuLosymOtwRM="

addons:
  coverity_scan:
    project:
      name: "konradrenner/jxattr"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command: mvn -f jxattr/pom.xml clean install -DskipTests=true -B -V
    branch_pattern: master
